import React from 'react';
import { Loader2, CheckCircle, XCircle, ArrowRight } from 'lucide-react';
import './PaymentStatus.css';

/**
 * PaymentStatusModal
 *
 * Props:
 *   status  — 'idle' | 'processing' | 'success' | 'failed'
 *   paymentId — Razorpay payment ID (shown on success)
 *   otp       — Handover code generated by backend (shown on success)
 *   onClose   — callback to close the modal
 */
const PaymentStatusModal = ({ status, paymentId, otp, onClose }) => {
  if (status === 'idle') return null;

  return (
    <div className="payment-modal-overlay">
      <div className="payment-modal-content">

        {/* PROCESSING */}
        {status === 'processing' && (
          <div className="status-step">
            <Loader2 size={48} className="spin" color="#003366" />
            <h3>Processing Payment...</h3>
            <p>Please do not close this window.</p>
            <div className="progress-bar">
              <div className="fill" style={{ width: '60%' }} />
            </div>
          </div>
        )}

        {/* SUCCESS */}
        {status === 'success' && (
          <div className="status-step success">
            <CheckCircle size={56} color="#166534" />
            <h2>Payment Successful!</h2>

            {paymentId && (
              <p className="tiny-text">
                Payment ID: <strong>{paymentId}</strong>
              </p>
            )}

            {otp && (
              <div className="otp-reveal-box">
                <span className="otp-label">YOUR HANDOVER CODE</span>
                <span className="otp-value">{otp}</span>
              </div>
            )}

            <p className="instruction">
              Share this code with the seller <b>only</b> when you meet in person.
            </p>

            <button className="finish-btn" onClick={onClose}>
              Go to My Purchases <ArrowRight size={16} />
            </button>
          </div>
        )}

        {/* FAILED */}
        {status === 'failed' && (
          <div className="status-step">
            <XCircle size={56} color="#dc2626" />
            <h3>Payment Failed</h3>
            <p>The payment was declined or cancelled. Please try again.</p>
            <button className="close-text-btn" onClick={onClose}>Close</button>
          </div>
        )}

      </div>
    </div>
  );
};

export default PaymentStatusModal;